services:
  - type: web
    name: wms-swagger-ui
    runtime: image
    image:
      url: docker.io/swaggerapi/swagger-ui:latest
    plan: free
    region: oregon
    envVars:
      - key: SWAGGER_JSON_URL
        value: https://raw.githubusercontent.com/heltonmarx/swagger/refs/heads/main/swagger.json
      - key: PORT
        value: 8080
