services:
  - type: web
    name: wms-swagger-ui
    runtime: image
    image:
      url: docker.io/swaggerapi/swagger-ui:latest
    plan: free
    region: oregon
    envVars:
      - key: SWAGGER_JSON_URL
        value: https://raw.githubusercontent.com/heltonmarx/wms/refs/heads/dev/swagger/swagger.json?token=GHSAT0AAAAAADZKVDZOSMRBDKCHMGGVMJVM2SMWETA
      - key: PORT
        value: 8080
